version: '3'
services:
  blog-back:
    image: runnermonster/blog-back:latest
    ports:
      - 3001:5000
    restart: always
    environment:
      - MONGO_URL=172.25.0.4:27017
    depends_on:
      - blog-mongodb
    networks:
      extnetwork:
        ipv4_address: 172.25.0.2
  blog-web:
    image: runnermonster/blog-web:latest
    ports:
      - 3000:3000
    restart: always
    networks:
      extnetwork:
        ipv4_address: 172.25.0.3
  blog-mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - /usr/local/workspace/mongo-data:/data/db
    networks:
      extnetwork:
        ipv4_address: 172.25.0.4
  blog-media:
    image: runnermonster/media:latest
    ports:
      - 3002:5001
    restart: always
    networks:
      extnetwork:
        ipv4_address: 172.25.0.5
  blog-nginx:
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - /usr/local/workspace/nginx:/etc/nginx/conf.d/
    networks:
      extnetwork:
        ipv4_address: 172.25.0.6
networks:
  extnetwork:
    ipam:
      config:
        - subnet: 172.25.0.0/16